const icon=(name)=>`<span class="ico">${{sound:'◖))',settings:'⚙',power:'◉',camera:'▣',eye:'◉',left:'‹',right:'›',reset:'↻',info:'i'}[name]}</span>`;
document.querySelector('#root').innerHTML=`<main><header><div class="brand"><div class="brandmark"><span></span></div><div><b>PARKWISE</b><small>DRIVING SIMULATOR</small></div></div><div class="step">LESSON 01 <i></i> <strong id="lesson">REVERSE PARK</strong></div><div class="topActions"><button id="sound">${icon('sound')}</button><button id="settings">${icon('settings')}</button><button class="exit">${icon('power')} EXIT</button></div></header>
<section class="cockpit"><div class="mirror left"><canvas data-view="rear"></canvas><span>OBJECTS IN MIRROR ARE CLOSER THAN THEY APPEAR</span></div><div class="rearMirror"><canvas data-view="rear"></canvas></div><div class="mirror right"><canvas data-view="rear"></canvas></div><div class="windshield"><canvas data-view="front"></canvas><div class="target"><span>PARK HERE</span></div><div class="scenarioTabs"><button class="active">Reverse park</button><button>Front-in</button><button>Parallel</button></div></div>
<aside class="miniViews"><div class="monitor" id="camera"><div class="monitorTitle">${icon('camera')} REAR CAMERA <button class="hide">×</button></div><div class="feed"><canvas data-view="rear"></canvas><div class="guide g1"></div><div class="guide g2"></div></div></div><div class="monitor" id="bird"><div class="monitorTitle">${icon('eye')} BIRD'S-EYE <button class="hide">×</button></div><div class="feed bird"><canvas data-view="bird"></canvas></div></div><div class="restore"></div></aside>
<div class="dash"><div class="wheel"><div></div><b>P</b></div><div class="cluster"><small>SPEED</small><strong>00</strong><span>km/h</span></div><div class="gear">${['P','R','N','D'].map(g=>`<button class="${g==='P'?'active':''}">${g}</button>`).join('')}</div></div></section>
<footer><div class="hint">${icon('info')}<span><b>YOUR GOAL</b> Reverse into the highlighted bay. Keep the vehicle fully between the yellow lines.</span></div><div class="controls"><button data-key="ArrowLeft">${icon('left')}</button><div class="keygroup"><button data-key="ArrowUp">↑</button><small>DRIVE</small></div><div class="keygroup"><button data-key="ArrowDown">↓</button><small>REVERSE</small></div><button data-key="ArrowRight">${icon('right')}</button><button class="reset">${icon('reset')} RESET</button></div></footer>
<div class="modalBackdrop" hidden><div class="modal"><button class="close">×</button><h2>Simulation settings</h2><p>Fine-tune the optical behavior of your driving aids.</p><label>Mirror fisheye <b><output>16</output>%</b></label><input id="fish" type="range" value="16" min="0" max="40"><label>Camera field of view <b>110°</b></label><input type="range" value="70"><button class="done">APPLY SETTINGS</button></div></div></main>`;
const state={x:0,z:7,angle:0,speed:0,gear:'P'},keys={},cars=[{x:-4,z:-23,c:'#1f2022'},{x:4,z:-23,c:'#e8e5dc'},{x:-4,z:-13,c:'#eeeae0'},{x:4,z:-3,c:'#17191b'}],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function reset(){Object.assign(state,{x:0,z:7,angle:0,speed:0,gear:'P'});renderDash()}
function car(ctx,x,y,w,h,c){ctx.save();ctx.translate(x,y);ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,5);ctx.fill();ctx.fillStyle='#9cbbc2';ctx.fillRect(-w*.36,-h*.28,w*.72,h*.25);ctx.fillStyle='#191b1c';ctx.fillRect(-w*.54,-h*.28,w*.1,h*.27);ctx.fillRect(w*.44,-h*.28,w*.1,h*.27);ctx.fillStyle='#bc3430';ctx.fillRect(-w*.37,h*.25,w*.18,4);ctx.fillRect(w*.19,h*.25,w*.18,4);ctx.restore()}
function topCar(ctx,x,y,c,hero){ctx.save();ctx.translate(x,y);ctx.fillStyle=hero?'#d5b58b':c;ctx.beginPath();ctx.roundRect(-13,-24,26,48,7);ctx.fill();ctx.fillStyle='#637276';ctx.fillRect(-10,-10,20,18);ctx.restore()}
function draw(c){const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const view=c.dataset.view,rear=view==='rear';if(view==='bird'){ctx.fillStyle='#768079';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.rotate(-state.angle);ctx.translate(-state.x*9,-state.z*6);ctx.strokeStyle='#e9b94c';ctx.lineWidth=2;for(let z=-30;z<18;z+=10)for(const x of[-7,-1,1,7]){ctx.beginPath();ctx.moveTo(x*9,z*6);ctx.lineTo(x*9,(z+8)*6);ctx.stroke()}cars.forEach(q=>topCar(ctx,q.x*9,q.z*6,q.c));ctx.restore();topCar(ctx,w/2,h/2,'#d5b58b',true);return}const sky=ctx.createLinearGradient(0,0,0,h*.55);sky.addColorStop(0,'#87969d');sky.addColorStop(1,'#d9d4c7');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.58);ctx.fillStyle='#777c75';ctx.fillRect(0,h*.55,w,h*.45);ctx.fillStyle='#59675e';ctx.fillRect(0,h*.53,w,h*.04);ctx.fillStyle='#b7b4aa';ctx.fillRect(0,h*.24,w*.26,h*.3);ctx.fillStyle='#c4beb0';ctx.fillRect(w*.72,h*.18,w*.28,h*.36);ctx.fillStyle='#292f2f';for(let x=10;x<w*.24;x+=26)for(let y=h*.28;y<h*.48;y+=27)ctx.fillRect(x,y,14,15);ctx.strokeStyle='#e9bd50';ctx.lineWidth=3;for(const x of[-.44,-.13,.13,.44]){ctx.beginPath();ctx.moveTo(w/2+x*w*.18,h*.55);ctx.lineTo(w/2+x*w*1.15,h);ctx.stroke()}for(let i=0;i<5;i++){let y=h*.58+i*i*h*.018;ctx.beginPath();ctx.moveTo(w*.13,y);ctx.lineTo(w*.87,y);ctx.stroke()}cars.map(q=>({...q,z:(rear?-q.z:q.z)-state.z,x:q.x-state.x})).filter(q=>q.z<0).sort((a,b)=>a.z-b.z).forEach(q=>{const dep=clamp((-q.z)/32,.08,1),sc=1-dep;car(ctx,w/2+q.x*42/(dep+.35),h*.56+sc*h*.35,22+sc*60,35+sc*65,q.c)});if(view==='front'){ctx.fillStyle='#242726';ctx.beginPath();ctx.moveTo(0,h);ctx.lineTo(0,h*.88);ctx.quadraticCurveTo(w*.5,h*.72,w,h*.88);ctx.lineTo(w,h);ctx.fill()}}
function renderDash(){document.querySelector('.cluster strong').textContent=Math.round(Math.abs(state.speed)*7).toString().padStart(2,'0');document.querySelector('.wheel').style.transform=`rotate(${state.angle*80}deg)`;document.querySelector('.wheel b').textContent=state.gear;document.querySelectorAll('.gear button').forEach(b=>b.classList.toggle('active',b.textContent===state.gear))}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key.startsWith('Arrow'))e.preventDefault()});addEventListener('keyup',e=>keys[e.key]=false);document.querySelectorAll('[data-key]').forEach(b=>{const set=v=>keys[b.dataset.key]=v;b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);set(true)};b.onpointerup=b.onpointercancel=()=>set(false)});document.querySelectorAll('.gear button').forEach(b=>b.onclick=()=>{state.gear=b.textContent;state.speed=0;renderDash()});document.querySelector('.reset').onclick=reset;
document.querySelectorAll('.scenarioTabs button').forEach(b=>b.onclick=()=>{document.querySelector('.scenarioTabs .active').classList.remove('active');b.classList.add('active');document.querySelector('#lesson').textContent=b.textContent.toUpperCase();reset()});document.querySelectorAll('.hide').forEach(b=>b.onclick=()=>{const box=b.closest('.monitor'),id=box.id;box.hidden=true;const r=document.querySelector('.restore'),bt=document.createElement('button');bt.innerHTML=(id==='camera'?icon('camera'):'')+(id==='bird'?icon('eye'):'')+' '+(id==='camera'?'Camera':"Bird's-eye");bt.onclick=()=>{box.hidden=false;bt.remove()};r.append(bt)});
const modal=document.querySelector('.modalBackdrop');document.querySelector('#settings').onclick=()=>modal.hidden=false;document.querySelectorAll('.close,.done').forEach(b=>b.onclick=()=>modal.hidden=true);document.querySelector('#fish').oninput=e=>document.querySelector('output').value=e.target.value;let muted=false;document.querySelector('#sound').onclick=e=>{muted=!muted;e.currentTarget.innerHTML=muted?'◖ ×':icon('sound')};
let last=performance.now();function loop(t){const dt=Math.min((t-last)/1000,.04);last=t;let acc=0;if(keys.ArrowUp){state.gear='D';acc=5}if(keys.ArrowDown){state.gear='R';acc=-4}state.speed+=(acc-state.speed*1.8)*dt;if(state.gear==='P')state.speed*=.82;if(keys.ArrowLeft)state.angle-=1.25*dt;if(keys.ArrowRight)state.angle+=1.25*dt;state.x+=Math.sin(state.angle)*state.speed*dt;state.z-=Math.cos(state.angle)*state.speed*dt;document.querySelectorAll('canvas').forEach(draw);renderDash();requestAnimationFrame(loop)}requestAnimationFrame(loop);
